# SwiftLint Configuration File
# For Hey Caddie iOS project

# Exclude folders that should not be linted
excluded:
  - Carthage
  - Pods
  - .build
  - Hey Caddie/Resources/Preview Content
  - Hey Caddie/Resources/Assets.xcassets
  - HeyCaddie/HeyCaddieTests
  - HeyCaddie/UnitTests
  - HeyCaddie/HeyCaddieUITests

# Opt-in rules for SwiftUI and modern Swift
opt_in_rules:
  - attributes
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases

# Disabled rules (customize as needed)
disabled_rules:
  - line_length # Allow longer lines for SwiftUI modifiers
  - todo # Allow TODOs in code
  - switch_case_on_newline
  - attributes
  - opening_brace # Ignore brace placement warnings
  - trailing_closure
  - function_default_parameter_at_end

# Custom rules for SwiftUI best practices
custom_rules:
  type_name_no_underscores:
    included: "Hey Caddie/App"
    name: "Type name should not contain underscores"
    regex: "struct [A-Za-z0-9_]+_+[A-Za-z0-9_]+" # Matches type names with underscores
    message: "Type names should not contain underscores. Use CamelCase."
    severity: error

# Reporter
reporter: xcode
